trigger: none
pool: default

variables:
  acrName: 'myacr5696'
  imageName: 'myapp-image'
  dockerfilePath: '**/Dockerfile'

stages:
- stage: buildAndPush
  jobs:
  - job: BuildJob
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '20.10.0'
    
    - powershell: |
        # Build the image
        docker build -t $(acrName).azurecr.io/$(imageName) -f $(dockerfilePath) .
        
        # Login to ACR (alternative method)
        $creds = az acr credential show -n $(acrName) --query passwords[0].value -o tsv
        docker login $(acrName).azurecr.io -u $(acrName) -p $creds
        
        # Push the image
        docker push $(acrName).azurecr.io/$(imageName):latest
      displayName: 'Build and Push with PowerShell'