trigger: none

pool: default

variables:
  acrName: 'myacr5696'
  repositoryName: 'myacr5696'

stages:
- stage: buildAndPush
  jobs:
  - job: BuildJob
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    
    # Remove the AzureCLI task that enables admin as we're using service principal
    
    - task: Docker@2
      inputs:
        containerRegistry: 'ACRServiceconnectionnight'
        repository: '$(repositoryName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(Build.BuildId)